# Generated by Django 4.2.3 on 2023-09-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='strava_user_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
