# Generated by Django 4.2.3 on 2023-09-11 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0002_alter_participant_strava_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lap',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
