# Generated by Django 4.2.3 on 2023-09-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0003_alter_lap_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='number',
            field=models.CharField(default='', max_length=3),
        ),
    ]
